"""make notes id an identity primary key

Revision ID: 43ecf0c09ee7
Revises: a4d7c9e2f615
Create Date: 2026-09-30 20:52:15.561041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ecf0c09ee7'
down_revision = 'a4d7c9e2f615'
branch_labels = None
depends_on = None


def upgrade():
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'Notes_pkey'
            ) THEN
                ALTER TABLE "Notes" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                ALTER TABLE "Notes" ADD CONSTRAINT "Notes_pkey" PRIMARY KEY (id);
            END IF;
        END $$;
        """
    )


def downgrade():
    op.execute('ALTER TABLE "Notes" DROP CONSTRAINT IF EXISTS "Notes_pkey"')
    op.execute('ALTER TABLE "Notes" ALTER COLUMN id DROP IDENTITY IF EXISTS')
