"""add default value to dashboard model


Revision ID: d1490a65be97
Revises: 2eed4c7932ec
Create Date: 2026-08-11 20:39:22.490267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1490a65be97'
down_revision = '2eed4c7932ec'
branch_labels = None
depends_on = None


def upgrade():
    # The previous revision already creates is_default. Skip when it is present
    # so a fresh database can apply this revision.
    bind = op.get_bind()
    columns = {column["name"] for column in sa.inspect(bind).get_columns("Dashboards")}
    if "is_default" not in columns:
        with op.batch_alter_table('Dashboards', schema=None) as batch_op:
            batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Dashboards', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
