"""Add invites references to dahsoard and user table

Revision ID: f8e6b2b2f9a7
Revises: 9cf7e98b4836
Create Date: 2026-08-23 14:19:26.482041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e6b2b2f9a7'
down_revision = '9cf7e98b4836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='invite_status'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['Dashboards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Invites_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_Invites_dashboard_id'), ['dashboard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Invites_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Invites_user_id'))
        batch_op.drop_index(batch_op.f('ix_Invites_dashboard_id'))
        batch_op.drop_index(batch_op.f('ix_Invites_created_at'))

    op.drop_table('Invites')
    # ### end Alembic commands ###
